@url=http://localhost:5226

###
GET {{url}}/Test

###
POST {{url}}/Test
Content-Type: application/json

{
  "name": "test",
  "description": "test",
  "parameterDto": {
    "test": "test"
  }
}

###
@id
###
GET {{url}}/Test/{{id}}

###
@id
###
GET {{url}}/Test/get-by-id-query?id={{id}}
