@url=http://localhost:5226


###
GET {{url}}/Test

###
POST {{url}}/Test
Content-Type: application/json

{
  "name": "test",
  "description": "test",
  "parameterDto": {
    "test": "test"
  }
}

###
@id

###
GET {{url}}/Test/parameter-in-route/{{id}}

###
@id

###
GET {{url}}/Test/parameter-in-query?id={{id}}

###
@id-parameter-in-query

###
POST {{url}}/Test/parameter-in-query?id-parameter-in-query={{id-parameter-in-query}}
Content-Type: application/json

{
  "name": "test",
  "description": "test",
  "parameterDto": {
    "test": "test"
  }
}

###
@id-parameter-in-route

###
POST {{url}}/Test/{id}/parameter-in-route
Content-Type: application/json

{
  "name": "test",
  "description": "test",
  "parameterDto": {
    "test": "test"
  }
}
